name: Telegram Bot Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Максимум 6 часов
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install python-telegram-bot psycopg2-binary
        
    - name: Run with auto-restart
      uses: nick-fields/retry@v2
      env:
        TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      with:
        timeout_minutes: 355  # Меньше 6 часов
        max_attempts: 3
        command: python bot.py
